# -*- coding: utf-8 -*-
"""temperature.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15oj7jXXyYTGK6s7YgVVCwsnL84QETTZr

Write a script called temperature.py that defines two functions:

convert_cel_to_far() which takes one float parameter representing degrees Celsius and returns a float representing the same temperature in degrees Fahrenheit using the following formula: F = C * 9/5 + 32
convert_far_to_cel() which take one float parameter representing degrees Fahrenheit and returns a float representing the same temperature in degrees Celsius using the following formula: C = (F - 32) * 5/9
The script should first prompt the user to enter a temperature in degrees Fahrenheit and then display the temperature converted to Celsius. Then prompt the user to enter a temperature in degrees Celsius and display the temperature converted to Fahrenheit. All converted temperatures should be rounded to 2 decimal places
"""

def convert_cel_to_far(c):
    f = c * 9/5 + 32
    return f
cel = float(input("Enter temperature in Celsius: "))
f = convert_cel_to_far(cel)
print("Temperature in Fahrenheit:", f)
def convert_far_to_cel(f):
    c = (f - 32) * 5/9
    return c
far = float(input("Enter temperature in Fahrenheit: "))
ff = convert_far_to_cel(far)
print("Temperature in Celsius:", ff)

1.